### PR TITLE
feat(fal): automatically lower max/min_concurrency for everyone other than falbot

### PR DESCRIPTION
**Pull request by efiop**

### CODE REVIEW

**Review by chamini2 — COMMENTED** [review]
We are actually about to give other users permissions to use bigger values than this, we cannot change this at client level

**Comment by efiop** [comment]
@chamini2 This is a convenience thing that was requested before. No way to show warnings from the backend to the SDK user, so the only other option than this pr would be to do that in the backend. I'm alright with that approach, happy to switch to that if you are in favor of that too.

**Comment by isidentical** [comment]
can we not run checks for these when people are doing `fal run`?

**Comment by isidentical** [comment]
I don't expect anyone to deploy anything from non-fal bot accounts. `fal run` covers %99 of the use cases

**Comment by efiop** [comment]
@isidentical Adjusted.

**Comment by efiop** [comment]
If only fal run is of concern then we could do that all on the backend indeed. And can even emit a log message with a warning from there. If everyone is ok with that, I'll send a PR instead of this one.

**Pull request closed without merging**
