### PR TITLE
ci: only run generate typing job when originating from upstream

### PR DESCRIPTION
**Pull request by isidentical**
It seems like the PRs coming from my fork fail at this stage, it is not big since we don't receive much outside contributions but just to make the CI green I think we can ignore this job on forks.

### CODE REVIEW

**Comment by isidentical** [comment]
From what I understood, it is for making the new commit trigger the CI: https://github.com/fal-ai/fal/pull/510#issue-1333816178

**Comment by chamini2** [comment]
You are right! I just found an issue which seems to make this work: https://github.com/stefanzweifel/git-auto-commit-action/issues/211

I think we need to move to checkout@v3 and remove the `token` from it. Can we try that?

**Comment by isidentical** [comment]
Trying it!

**Comment by isidentical** [comment]
Seems to be working, thanks again @chamini2!

**Pull request merged**
