### PR TITLE
fix: Handle partially-applied write_to_model before scripts in typing module

### PR DESCRIPTION
**Pull request by chamini2**
image

### CODE REVIEW

**Comment by isidentical** [comment]
@chamini2 can you share some context on what is the issue (I am not really familiar with the implementation of `write_to_model`).

**Comment by chamini2** [comment]
https://github.com/fal-ai/fal/blob/main/src/fal/fal_script.py#L115-L119

This happens before the script starts, we don't really send the FalDbt version down to the script.

**Comment by isidentical** [comment]
Ah, that's interesting thanks!!

**Comment by isidentical** [comment]
@chamini2 since this is a very specific case and handling of this inside the function is very convoluted as you noted, would it make sense to statically embed this just like `context`? Like this https://gist.github.com/isidentical/d337d0e2e6597bc3ef3ca2a097150a81

**Comment by chamini2** [comment]
> @chamini2 since this is a very specific case and handling of this inside the function is very convoluted as you noted, would it make sense to statically embed this just like `context`? Like this https://gist.github.com/isidentical/d337d0e2e6597bc3ef3ca2a097150a81
> 
> I am fine with this version too (it preserves the doc-strings and other changes in the future, so we might just bear the complexity), the example above is just a suggestion to your todo comment.

Let's go this way, but your suggestion is not bad to be honest. We can do that later if we feel it's not worth keeping.

**Comment by chamini2** [comment]
> @chamini2 since this is a very specific case and handling of this inside the function is very convoluted as you noted, would it make sense to statically embed this just like `context`? Like this https://gist.github.com/isidentical/d337d0e2e6597bc3ef3ca2a097150a81
> 
> I am fine with this version too (it preserves the doc-strings and other changes in the future, so we might just bear the complexity), the example above is just a suggestion to your todo comment.

I liked this. Done!

**Review by isidentical — APPROVED** [review]

**Pull request merged**
