### PR TITLE
refactor: move env var to ignore fal keys to flags.py

### PR DESCRIPTION
**Pull request by chamini2**

### CODE REVIEW

**Review by efiop — APPROVED** [review]
💅

**Comment by efiop** [comment]
Looks like mypy is not happy about mainify. Unrelated to this PR, I'll take a look on top.

**Comment by chamini2** [comment]
oook, now I see why we did not do this before. We mainify this function and run it in the remote env, so we must run `os.environ` check separately and not use any fal deps inside of it

**Comment by efiop** [comment]
Hm, tests are failing - might be that the module triggered a need to do mainify here too, I'll need to check. I guess another reason to hurry up with ckoudlickle.

**Pull request closed without merging**
